# Generated by Django 6.1.1 on 2026-09-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name_plural': 'Votes'},
        ),
    ]
